M48
; DRILL file {KiCad (6.0.1-0)} date 2022 January 31, Monday 23:33:03
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-31T23:33:03+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0748
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
%
G90
G05
T1
X3.8Y-3.1
X3.8Y-3.85
X3.8Y-4.6
X3.8Y-5.35
X4.2Y-3.1
X4.2Y-3.85
X4.2Y-4.6
X4.2Y-5.35
T2
X3.85Y-3.0
X3.85Y-3.75
X3.85Y-4.5
X3.85Y-5.25
X4.1Y-2.9
X4.1Y-3.65
X4.1Y-4.4
X4.1Y-5.15
T3
X4.0Y-3.1
X4.0Y-3.85
X4.0Y-4.6
X4.0Y-5.35
T0
M30
